export const WORLD = {
  TILE_SIZE: 1,
  CHUNK_SIZE: 16,
} as const;

export const CAMERA = {
  MIN_ZOOM: 3,
  MAX_ZOOM: 30,
  DEFAULT_ALPHA: -Math.PI / 2,
  DEFAULT_BETA: Math.PI / 3,
  DEFAULT_RADIUS: 20,
  ANGULAR_SENSIBILITY: 500,
  ORBIT_SPEED: 0.02,
  WHEEL_PRECISION: 30,
} as const;

const PLAYER_HEIGHT = 1.8;
const FLOOR_HEIGHT = PLAYER_HEIGHT + 0.5;

export const PLAYER = {
  SIZE: 0.75,
  HEIGHT: PLAYER_HEIGHT,
  Y_OFFSET: PLAYER_HEIGHT / 2,
  LERP_SPEED: 0.12,
} as const;

export const FLOOR = {
  HEIGHT: FLOOR_HEIGHT,
  FIRST_FLOOR: FLOOR_HEIGHT,
  SECOND_FLOOR: FLOOR_HEIGHT * 2,
  THIRD_FLOOR: FLOOR_HEIGHT * 3,
} as const;

export const MOVEMENT = {
  BASE_SPEED: 4,
  TILE_DURATION_MS: 250,
} as const;
