/*
 Generated by typeshare 1.13.4
*/

/**
 * Cardinal facing direction as a u8. 0 = N, 1 = S, 2 = E, 3 = W.
 * Kept as a plain number so typeshare emits `number` rather than a broken string enum.
 */
export type Direction = number;

/**
 * Ephemeral per-connection identifier assigned by the server on join.
 * Not persisted - resets on every connect. Used to reference players
 * in all real-time WS messages for the duration of a session.
 */
export type SessionId = number;

/**
 * 3D tile coordinate in world space.
 * One unit equals one tile. x increases east, z increases south.
 * y is the floor level: 0 = surface, positive = above ground, negative = underground.
 * y is discrete - players snap between floors with no partial values.
 */
export interface Coords {
	x: number;
	y: number;
	z: number;
}

/**
 * Client → Server: player requests movement.
 * Fields: dest (target tile), path (ordered waypoints, max MAX_PATH_LENGTH), pace (ms/tile).
 */
export interface MoveMessage {
	dest: Coords;
	path: Coords[];
	pace: number;
}

/**
 * Full player record. Loaded from DynamoDB on connect and held in memory
 * for the lifetime of the session. Persisted back to DynamoDB on disconnect.
 * Fields: uuid (Cognito sub / DynamoDB pk), player_name, coords, facing.
 */
export interface Player {
	uuid: string;
	player_name: string;
	coords: Coords;
	facing: Direction;
}

/**
 * Server → all clients: a new player has entered the world.
 * Fields: msg_type, id (session ID of joining player), player (full record for immediate render).
 */
export interface PlayerJoinMessage {
	type: Opcode;
	id: SessionId;
	player: Player;
}

/**
 * Server → all clients: a player has left the world.
 * Fields: msg_type, id (session ID of the player who left).
 */
export interface PlayerLeaveMessage {
	type: Opcode;
	id: SessionId;
}

/**
 * Server → originating client: authoritative result of a move request.
 * If `accepted` is false the client must snap back to `coords`.
 * Fields: msg_type, accepted, coords (authoritative position), pace (ms/tile, meaningful on accept only),
 * path (confirmed waypoints, empty on reject), facing.
 */
export interface PlayerMoveResultMessage {
	type: Opcode;
	accepted: boolean;
	coords: Coords;
	pace: number;
	path: Coords[];
	facing: Direction;
}

/**
 * Server → Client: session accepted.
 * Sent immediately after a valid `SessionConnect`.
 * Fields: msg_type, id (ephemeral session ID), server_id, player (full initial state).
 */
export interface SessionAcceptedMessage {
	type: Opcode;
	id: SessionId;
	server_id: number;
	player: Player;
}

/**
 * Client → Server: authenticate and join the world.
 * Sent as the first message on every new connection.
 * Token format: `<uuid>.<expiry_ms>.<hex_hmac_sha256_of_"uuid.expiry_ms">`
 */
export interface SessionConnectMessage {
	token: string;
	server_id: number;
}

/**
 * Server → Client: session rejected. Connection is closed after this message.
 * Fields: msg_type, message (human-readable reason).
 */
export interface SessionRejectedMessage {
	type: Opcode;
	message: string;
}


/** 
 * Opcode - appended by gen (typeshare cannot emit numeric enums)
 * Source of truth: server/src/msg/opcodes.rs
 */
export const Opcode = {
  SessionConnect: 100,
  SessionAccepted: 101,
  SessionRejected: 102,
  PlayerJoin: 200,
  PlayerLeave: 201,
  PlayerMove: 202,
  PlayerMoveResult: 203,
} as const;

export type Opcode = typeof Opcode[keyof typeof Opcode];
